### ISSUE TITLE
Some errors at startup

### ISSUE THREAD

**Issue by fabrizioschiavi** [guidoferreyra/showCoordinates#3]
![Screenshot 2019-12-28 at 18 45 14](https://user-images.githubusercontent.com/1576663/71548492-49a83f00-29af-11ea-9111-a01a0f1dcab6.png)
![Screenshot 2019-12-28 at 18 45 38](https://user-images.githubusercontent.com/1576663/71548494-4c0a9900-29af-11ea-81e9-e3a7e8187a33.png)
This happens since Mac OS Catalina update.
Thanks for this super-useful plugin!

**Comment by guidoferreyra** [comment]
Hi Fabrizio,
Reagarding the first message alert, I understood if you install the plugin via the Plugin manager you will not have that issue. Is the plugin working for you?

Now the second alert, is because I have to update the plugin to the current API, It should‘t affect the plugin functions but  know that is super annoying to start Glyphs and have this alert everytime. I will try to update it ASAP.

Best.

**Comment by guidoferreyra** [comment]
This should be fixed by installing the plugin via Glyphs plugin manager and the plugin wa updated to avoid the Glyph alert. Please let me know if it is working for you.
